### ISSUE TITLE
Mysterious error on running flatpak: undefined symbol: _PyObject_CallNoArg

### ISSUE THREAD

**Issue by j5155** [iwalton3/tkinter-standalone#6]
I added this to my Flatpak project that uses Tkinter, and it builds successfully, but when I run it I get this error:
```
Traceback (most recent call last):
  File "<frozen runpy>", line 198, in _run_module_as_main
  File "<frozen runpy>", line 88, in _run_code
  File "/app/lib/python3.11/site-packages/REVHubInterface/__main__.py", line 1, in <module>
    import tkinter
  File "/app/lib/python3.11/site-packages/tkinter/__init__.py", line 36, in <module>
    import _tkinter # If this fails your Python may not be configured for Tk
    ^^^^^^^^^^^^^^^
ImportError: /app/lib/python3.11/site-packages/_tkinter.cpython-311-x86_64-linux-gnu.so: undefined symbol: _PyObject_CallNoArg
```
Project at https://github.com/unofficial-rev-port/REVHubInterface/
Replication steps:
Clone the project.
Enter the flatpak folder.
Run `flatpak-builder --user --install build org.unofficialrevport.REVHubInterface.yml --force-clean`, which should build and install successfully.
Run `flatpak run org.unofficialrevport.REVHubInterface`
See error.

Not sure whether this is an issue with tkinter-standalone, the flatpak setup, or the installation on my PC, but would appreciate some help either way.

**Comment by j5155** [comment]
Needed to change the building steps to reference the latest commit on this repository.
